# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[31,)" #mandatory
# A text field displayed in the mod UI
credits="Michael Hillox" #optional
# A text field displayed in the mod UI
authors="Michael Hillcox" #optional
license="GNU GPL v3.0 (https://github.com/MichaelHillcox/XRay-Mod/blob/master/LICENSE)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
    # The modid of the mod
    modId="xray" #mandatory
    # The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
    version="${file.jarVersion}" #mandatory
     # A display name for the mod
    displayName="Advanced XRay" #mandatory
    # The description text for the mod (multi line!) (#mandatory)
    description="An advanced XRay mod for Minecraft."